name: Delete Artifacts

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type YES to confirm artifact deletion'
        required: true
        default: 'NO'

jobs:
  delete-artifacts:
    if: ${{ github.event.inputs.confirm == 'YES' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List and delete artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        artifacts=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts | .[] | .id')
        for artifact_id in $artifacts; do
          echo "Deleting artifact $artifact_id"
          curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id
        done
