name: Google Gemini Integration

on: [workflow_dispatch]

jobs:
  gemini_integration:
    runs-on: self-hosted 
    permissions:
      contents: write 
      actions: write 

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Commit Message and Changed File Diffs
      id: commit_info
      run: |
        # Get the latest commit message
        commit_message=$(git log -1 --pretty=%B)
        
        # Get the list of files changed in the latest commit
        changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD)

        # Export commit message and changed files as environment variables
        echo "commit_message<<EOF" >> $GITHUB_ENV
        echo "$commit_message" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        echo "changed_files<<EOF" >> $GITHUB_ENV
        echo "$changed_files" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        # Retrieve only the changes (diffs) made in each file
        file_diffs=""
        for file in $changed_files; do
          diff=$(git diff HEAD~1 HEAD -- "$file")
          if [ -n "$diff" ]; then
            file_diffs="$file_diffs\n---\nFile: $file\n$diff"
          fi
        done

        # Export file diffs as a multi-line environment variable
        echo "file_diffs<<EOF" >> $GITHUB_ENV
        echo -e "$file_diffs" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Use Commit Message and Extracted Text
      run: |
        commit_message="${{ env.commit_message }}"
        file_diffs="${{ env.file_diffs }}"
        
        echo "Commit Message: $commit_message"
        echo -e "File Diffs: $file_diffs"



    - name: Make Request to Gemini
      id: gemini_request
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        commit_message: ${{ env.commit_message }}
        file_diffs : ${{ env.file_diffs }}
        
      run: |
        cleaned_file_diffs=$(echo -e "${{ env.file_diffs }}" | tr '\n' ' ')
        
        response=$(curl -s -H "Content-Type: application/json" \
        -d '{"contents":[{"parts":[{"text":"${{ vars.GEMINI_PROMPT_ACTIONS }} - ${{ env.commit_message }}, and here are the changed file details - $cleaned_file_diffs "}]}]}' \
        -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=$GEMINI_API_KEY")

        # Get Text from Response
        text=$(echo "$response" | jq -r '.candidates[0].content.parts[0].text')
        
        echo "extracted_text<<EOF" >> $GITHUB_ENV
        echo "$text" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
    - name: Use Gemini Response
      run: |
        echo "Response: $extracted_text"
      env:
        response: ${{ env.extracted_text }}


    # - name: Trigger DMG Release
    #   uses: actions/github-script@v7
    #   with:
    #     script: |
    #       await github.rest.actions.createWorkflowDispatch({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         workflow_id: 'release-dmg.yml',
    #         ref: 'main',
    #         inputs: {
    #           release_name: "New Release",
    #           release_description: process.env.extracted_text,
    #           release_tag: "v1.0.0"
    #         }
    #       });
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     extracted_text: ${{ env.extracted_text }}
