name: Build and Release macOS DMG

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Release Name"
        required: true
        default: "New Release"
      release_description:
        description: "Description"
        required: false
        default: "Description of the release"
      release_tag:
        description: "The tag for the release"
        required: true
        default: "v1.0.0"

jobs:
  build:
    #runs-on: macos-15
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Decode and Save Info.plist
        env:
          ENCODED_INFO_PLIST: ${{ secrets.ENCODED_INFO_PLIST }}
          ENCODED_GOOGLESERVICE_PLIST: ${{ secrets.ENCODED_GOOGLESERVICE_PLIST }}
          ENCODED_SECRETS_PLIST: ${{ secrets.ENCODED_SECRETS_PLIST }}
        run: |
          echo "$ENCODED_INFO_PLIST" | base64 --decode > ${{ vars.SCHEME_NAME }}/Info.plist
          echo "$ENCODED_GOOGLESERVICE_PLIST" | base64 --decode > ${{ vars.SCHEME_NAME }}/GoogleService-Info.plist
          echo "$ENCODED_SECRETS_PLIST" | base64 --decode > ${{ vars.SCHEME_NAME }}/Secrets.plist

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Clean Build Directory
        run: rm -rf ./build

      - name: Resolve SwiftPM Dependencies
        run: swift package resolve

          
      - name: Build
        run: |
          xcodebuild -scheme ${{ vars.SCHEME_NAME }} -project ${{ vars.XCODEPROJ }} -configuration Release -derivedDataPath ./build CODE_SIGNING_ALLOWED=NO -allowProvisioningUpdates

      - name: Create DMG
        run: |
          hdiutil create -volname ${{ vars.SCHEME_NAME }} -srcfolder build/Build/Products/Release/${{ vars.SCHEME_NAME }}.app -ov -format UDZO "${{ vars.SCHEME_NAME }}.dmg"

      - name: Upload DMG as artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ vars.SCHEME_NAME }}.dmg"
          path: ${{ vars.SCHEME_NAME }}.dmg

      - name: Create Release and Upload DMG
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release_tag }} 
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_description }}
          files: ${{ vars.SCHEME_NAME }}.dmg
          
